# -*- coding: utf-8 -*-
"""task2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EuU7msfvH-T0zQHyX0PKomMn6IKfEvs2
"""

'''
This notebook is the second part of the DCIT 412 class activity
'''

# Import Required Libraries
import cv2
from google.colab.patches import cv2_imshow
import matplotlib.pyplot as plt

# Load image
image = cv2.imread("photo.jpg")

# Convert color spaces
gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
hsv = cv2.cvtColor(image, cv2.COLOR_BGR2HSV)
lab = cv2.cvtColor(image, cv2.COLOR_BGR2LAB)

# Save converted images
cv2.imwrite("photo_grayscale.jpg", gray)
cv2.imwrite("photo_hsv.jpg", hsv)
cv2.imwrite("photo_lab.jpg", lab)

# Display images
# from google.colab.patches import cv2_imshow
cv2_imshow(gray)
cv2_imshow(hsv)
cv2_imshow(lab)

# Plot histogram for grayscale
plt.figure()
plt.title("Grayscale Histogram")
plt.xlabel("Pixel Intensity")
plt.ylabel("Frequency")
plt.hist(gray.ravel(), 256, [0, 256])

# Save the graph
plt.savefig("photo_grayscale_histogram.jpg")

# Display the image
plt.show()

cv2.waitKey(0)
cv2.destroyAllWindows()

# End of Notebook