# -*- coding: utf-8 -*-
"""task1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EuU7msfvH-T0zQHyX0PKomMn6IKfEvs2
"""

'''
This notebook is the first part of the DCIT 412 class activity
'''

# Import Required Libraries
import cv2
from google.colab.patches import cv2_imshow

# Load the original image
image = cv2.imread("photo.jpg")

# Convert to grayscale
gray_image = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)

# Show both images
cv2_imshow(image)
cv2_imshow(gray_image)

# Save grayscale image
cv2.imwrite("photo_gray.jpg", gray_image)

cv2.waitKey(0)
cv2.destroyAllWindows()

# End of Notebook